name: Install Python with conda and uv
description: |
  This GitHub Action installs Python using conda/mamba.
  It pins the specified Python version and installs dependencies.

inputs:
  python-version:
    description: Python version
    required: true

  conda-env-name:
    description: Conda environment name
    required: false
    default: absmt

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: ${{ inputs.conda-env-name }}

    - name: Get Python path
      id: get-python
      run: echo "PYTHON_PATH=$(which python)" >> $GITHUB_ENV
      shell: bash -el {0}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install dependencies with uv
      run: |
        uv pip sync pyproject.toml
        uv pip install --group dev-dependencies -r pyproject.toml
        uv pip install .
      shell: bash -el {0}
      env:
        UV_PYTHON: ${{ env.PYTHON_PATH }}
