[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graduation-thesis"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "tanashou", email = "" }
]
dependencies = [
    "automata-lib[visual]>=8.1.0",
]
readme = "README.md"
requires-python = ">= 3.8"
license = { file = "LICENSE" }

[project.optional-dependencies]
dev = [
    "mypy>=1.7.1",
    "pytest>=7.4.3",
]

[tool.hatch.build.targets.wheel]
packages = ["src/graduation_thesis"]

[tool.hatch.envs.default]
dependencies = [
    "pytest",
    "pytest-cov",
]

[tool.hatch.envs.default.scripts]
test = "pytest tests/ {args}"
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=src/graduation_thesis --cov=tests {args}"

[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.hatch.metadata]
allow-direct-references = true