from enum import StrEnum, auto


class SMTLIBv2Type(StrEnum):
    Comment = auto()
    ParOpen = auto()
    ParClose = auto()
    Semicolon = auto()
    String = auto()
    QuotedSymbol = auto()
    PS_Not = "not"
    PS_Bool = "Bool"
    PS_ContinuedExecution = "continued-execution"
    PS_Error = "error"
    PS_False = "false"
    PS_ImmediateExit = "immediate-exit"
    PS_Incomplete = "incomplete"
    PS_Logic = "logic"
    PS_Memout = "memout"
    PS_Sat = "sat"
    PS_Success = "success"
    PS_Theory = "theory"
    PS_True = "true"
    PS_Unknown = "unknown"
    PS_Unsupported = "unsupported"
    PS_Unsat = "unsat"
    CMD_Assert = "assert"
    CMD_CheckSat = "check-sat"
    CMD_CheckSatAssuming = "check-sat-assuming"
    CMD_DeclareConst = "declare-const"
    CMD_DeclareDatatype = "declare-datatype"
    CMD_DeclareDatatypes = "declare-datatypes"
    CMD_DeclareFun = "declare-fun"
    CMD_DeclareSort = "declare-sort"
    CMD_DefineFun = "define-fun"
    CMD_DefineFunRec = "define-fun-rec"
    CMD_DefineFunsRec = "define-funs-rec"
    CMD_DefineSort = "define-sort"
    CMD_Echo = "echo"
    CMD_Exit = "exit"
    CMD_GetAssertions = "get-assertions"
    CMD_GetAssignment = "get-assignment"
    CMD_GetInfo = "get-info"
    CMD_GetModel = "get-model"
    CMD_GetOption = "get-option"
    CMD_GetProof = "get-proof"
    CMD_GetUnsatAssumptions = "get-unsat-assumptions"
    CMD_GetUnsatCore = "get-unsat-core"
    CMD_GetValue = "get-value"
    CMD_Pop = "pop"
    CMD_Push = "push"
    CMD_Reset = "reset"
    CMD_ResetAssertions = "reset-assertions"
    CMD_SetInfo = "set-info"
    CMD_SetLogic = "set-logic"
    CMD_SetOption = "set-option"
    GRW_Exclamation = "!"
    GRW_Underscore = "_"
    GRW_As = "as"
    GRW_Binary = "BINARY"
    GRW_Decimal = "DECIMAL"
    GRW_Exists = "exists"
    GRW_Hexadecimal = "HEXADECIMAL"
    GRW_Forall = "forall"
    GRW_Let = "let"
    GRW_Match = "match"
    GRW_Numeral = "NUMERAL"
    GRW_Par = "par"
    GRW_String = "string"
    Numeral = auto()
    Binary = auto()
    HexDecimal = auto()
    Decimal = auto()
    Colon = ":"
    PK_AllStatistics = ":all-statistics"
    PK_AssertionStackLevels = ":assertion-stack-levels"
    PK_Authors = ":authors"
    PK_Category = ":category"
    PK_Chainable = ":chainable"
    PK_Definition = ":definition"
    PK_DiagnosticOutputChannel = ":diagnostic-output-channel"
    PK_ErrorBehaviour = ":error-behavior"
    PK_Extension = ":extensions"
    PK_Funs = ":funs"
    PK_FunsDescription = ":funs-description"
    PK_GlobalDeclarations = ":global-declarations"
    PK_InteractiveMode = ":interactive-mode"
    PK_Language = ":language"
    PK_LeftAssoc = ":left-assoc"
    PK_License = ":license"
    PK_Named = ":named"
    PK_Name = ":name"
    PK_Notes = ":notes"
    PK_Pattern = ":pattern"
    PK_PrintSuccess = ":print-success"
    PK_ProduceAssertions = ":produce-assertions"
    PK_ProduceAssignments = ":produce-assignments"
    PK_ProduceModels = ":produce-models"
    PK_ProduceProofs = ":produce-proofs"
    PK_ProduceUnsatAssumptions = ":produce-unsat-assumptions"
    PK_ProduceUnsatCores = ":produce-unsat-cores"
    PK_RandomSeed = ":random-seed"
    PK_ReasonUnknown = ":reason-unknown"
    PK_RegularOutputChannel = ":regular-output-channel"
    PK_ReproducibleResourceLimit = ":reproducible-resource-limit"
    PK_RightAssoc = ":right-assoc"
    PK_SmtLibVersion = ":smt-lib-version"
    PK_Sorts = ":sorts"
    PK_SortsDescription = ":sorts-description"
    PK_Source = ":source"
    PK_Status = ":status"
    PK_Theories = ":theories"
    PK_Values = ":values"
    PK_Verbosity = ":verbosity"
    PK_Version = ":version"
    UndefinedSymbol = auto()
    WS = auto()

    # custom type
    INT = "Int"
    AND = "and"
    OR = "or"
    TIMES = "*"
    MINUS = "-"
    EQUAL = "="
    GREATER_EQUAL = ">="
    LESS_EQUAL = "<="
    LESS_THAN = "<"
    GREATER_THAN = ">"


# Create a dictionary mapping values to enum members
value_to_member_map = {member.value: member for member in SMTLIBv2Type}


def get_SMTLIBv2Type_by_value(value: str) -> SMTLIBv2Type | None:
    return value_to_member_map.get(value)
