name: Ruff

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python with conda
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint
        run: |
          uv pip install ruff
          ruff check --output-format=github .
        shell: bash -el {0}

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python with conda
        uses: ./.github/actions/setup-python-with-uv

      - name: Format
        run: |
          uv pip install ruff
          ruff format . --check --diff
        shell: bash -el {0}
